--------------------------------------------------------
-- Archivo creado  - martes-agosto-23-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SEGUROMEDICO
--------------------------------------------------------

  CREATE TABLE "SEGUROMEDICO"."SEGUROMEDICO" 
   (	"IDSEGUROMEDICO" NUMBER(11,0), 
	"NIF" VARCHAR2(10 BYTE), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"APE1" VARCHAR2(50 BYTE), 
	"EDAD" NUMBER(3,0), 
	"SEXO" VARCHAR2(20 BYTE), 
	"CASADO" NUMBER(1,0), 
	"NUMHIJOS" NUMBER(3,0), 
	"EMBARAZADA" NUMBER(1,0), 
	"COBERTURAOFTALMOLOGICA" NUMBER(1,0), 
	"COBERTURADENTAL" NUMBER(1,0), 
	"COBERTURAFECUNDACIONINVITRO" NUMBER(1,0), 
	"ENFERMEDADCORAZON" NUMBER(1,0), 
	"ENFERMEDADESTOMACAL" NUMBER(1,0), 
	"ENFERMEDADRINYONES" NUMBER(1,0), 
	"ENFERMEDADALERGIA" NUMBER(1,0), 
	"NOMBREALERGIA" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SEGUROMEDICO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEGUROMEDICO"."SEGUROMEDICO_PK" ON "SEGUROMEDICO"."SEGUROMEDICO" ("IDSEGUROMEDICO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SEGUROMEDICO
--------------------------------------------------------

  ALTER TABLE "SEGUROMEDICO"."SEGUROMEDICO" ADD CONSTRAINT "SEGUROMEDICO_PK" PRIMARY KEY ("IDSEGUROMEDICO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SEGUROMEDICO"."SEGUROMEDICO" MODIFY ("IDSEGUROMEDICO" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Trigger TIB_NEWREGISTRO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SEGUROMEDICO"."TIB_NEWREGISTRO" 
   before insert on "SEGUROMEDICO"."SEGUROMEDICO" 
   for each row 
begin  
   if inserting then 
      if :NEW."IDSEGUROMEDICO" is null then 
         select SEC_NEWREGISTRO.nextval into :NEW."IDSEGUROMEDICO" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "SEGUROMEDICO"."TIB_NEWREGISTRO" ENABLE;
